language: java
jdk: oraclejdk8
 
addons:
  sonarcloud:
    organization: pablohenriquemg-github
    token:
      secure: 56b22c3bf240477a1e044edf5deb62db171bbe55
 
script:
- ./mvnw clean install -B
- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
