language: java
jdk: oraclejdk8

env:
  global:
  - secure: 56b22c3bf240477a1e044edf5deb62db171bbe55
 
addons:
  sonarcloud:
    organization: pablohenriquemg-github
    token:
      secure: $SONAR_TOKEN
 
script:
- ./mvnw clean install -B
- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
